name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: '20' # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
